<script setup lang="ts">
import { useServiceStore } from "../stores/serviceStore";

const serviceStore = useServiceStore();

function goToCompete() {
  serviceStore.selectedRoute = 'Compete'
}

</script>

<template>
  <main>
    <h3 class="mb-4">How i did it / Step by step Summary</h3>
    <p>
      I copied the Advanced Forms project from the html folder you sent me and put it over my newly created Vue3
      Typescript
      app.
    </p>

    <p>
      Technologies used: Vue3 script setup, Typescript, Pinia.
      Validation: yup
    </p>

    <p>
      I filtered the example and kept only the components i was going to use, then created fully reactive Vue compoenents
      out of them
      that are preapred to be linked with the v-model.
    </p>

    <p>
      I prepared the grip for the app keeping it similar to the examples you sent , preparing the 2 routes 'Details' and
      'Compete' that you can see on the left Navbar.
    </p>

    <p>
      I separated as much of the code into reusable components so that the main components are clean and easy to read.
    </p>

    <p>
      On the 'Compete' route you can find the actual task implementation.
    </p>

    <p>
      I created a modal that holds my wizard.
    </p>

    <p>
      Inside it there is a wizard component that dynamically generates a wizard depending on a wizard config. Depending on
      the reactive CurrentWizardStep the corresponding Step
    </p>

    <p>Step 1</p>
    <p>
    <ul>
      <li>2 textboxes and 1 textare all generated by the same dynamic component</li>
      <li>validation done with validationSchema from yup</li>
    </ul>
    </p>

    <p>Step 2</p>
    <p>
    <ul>
      <li>2 pair of 2 fancy radio buttons but i applied btn classes on them to keep the similarities with the live website
      </li>
      <li>2 vue3 reactive customdatepicker</li>
      <li>2 dynamic dropdowns with your design</li>
      <li>validation is made the same way with yup</li>
    </ul>
    </p>

    <p>Step 3</p>
    <p>
    <ul>
      <li>i created 2 button that will allow you to choose the wanted filter Skills or Difficultis&Tags</li>
      <li>to get the data for the dropdowns options i had to use the Api Routes you sent</li>
      <li>because of the 'Access-Control-Allow-Origin' i had to get them by creating json files which i later import</li>
      <li>to mimic the behavior of a normal fetch and to prove the concept of promises, async , await i created a mock
        method that returns a promise with the data from the Json files</li>
      <li>because i had some issues with the reactivity or intercativity with you Multiselect componenets i had to create
        my
        own that do exactly the same</li>
      <li>at this step i handled the validation inside the customed componenets with max min properties and with a
        computed
        onthe step</li>
      <li>the filtering is done with watches and computed</li>
    </ul>
    </p>

    <p>Summary</p>
    <p>
    <ul>
      <li>it bejaves like a step and it is generated from the config</li>
      <li>list of what the user completed in the form</li>
      <li>when you finish the event will be saved in the store</li>
      <li>you can see the newly created event in the table underneath the button that opens the modal. Just close the
        modal
        and see for yourself</li>
    </ul>
    </p>
    <button @click="goToCompete" class="btn btn-round btn-info mb-4">
      Go To Compete
    </button>
  </main>
</template>

